[package]
authors = { workspace = true }
description = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
name = "alpha-omega"
repository = { workspace = true }
version = "0.0.1"

[dependencies]
app = { path = "./app" }
db = { path = "./db" }
server = { path = "./server" }

axum = { workspace = true, optional = true }
deadpool-postgres = { workspace = true, optional = true }
dioxus = { workspace = true }
dotenvy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }
tracing-wasm = { version = "0.2.1", optional = true }

[features]
desktop = ["dioxus/desktop", "shared"]
mobile = ["dioxus/mobile", "shared"]
server = ["dep:axum", "dep:deadpool-postgres", "dep:tokio", "dep:tracing", "dep:tracing-subscriber", "dioxus/axum", "shared"]
shared = ["dioxus/devtools", "dioxus/fullstack", "dioxus/router", "dioxus/ssr"]
web = ["dep:tracing-wasm", "dioxus/web", "shared"]
